# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlueCli < Formula
  desc "CLI for Blue workspace management"
  homepage "https://blue.cc"
  version "0.4.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyblueteam/cli/releases/download/v0.4.0/blue_darwin_amd64.tar.gz"
      sha256 "3bf7bb72edc939d2485de15645ee5ef818f193879ee126847c13cab0865f21ff"

      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyblueteam/cli/releases/download/v0.4.0/blue_darwin_arm64.tar.gz"
      sha256 "6f0cb3bbbd26c981d0e61c90837723dd8d305a0e09751878f4674694751d6807"

      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.4.0/blue_linux_amd64.tar.gz"
      sha256 "e517760229762176a5a36b6952c8a49ebbe99403a91faf96122218ffa41ff5fd"
      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.4.0/blue_linux_arm64.tar.gz"
      sha256 "e5a0236fbc77bc9d9f06c628b948ae4ef5e31df69c2c8b123f6dd3683094a6e2"
      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  test do
    system "#{bin}/blue", "version"
  end
end
