# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlueCli < Formula
  desc "CLI for Blue workspace management"
  homepage "https://blue.app"
  version "0.13.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyblueteam/cli/releases/download/v0.13.1/blue_darwin_amd64.tar.gz"
      sha256 "8c5f10982d67d067793982e41100f7bd16ea6471e3f815d76b8339977d0e4dd2"

      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyblueteam/cli/releases/download/v0.13.1/blue_darwin_arm64.tar.gz"
      sha256 "f63139e139aeb3fc8b399f580f8fdab2df8f5ef564d4cde64c537064e7fdcf90"

      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.13.1/blue_linux_amd64.tar.gz"
      sha256 "c06ea1f9b6c1631444dfc9992c6f9f29e246848ef09cf877c2419e5e83b44e15"
      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.13.1/blue_linux_arm64.tar.gz"
      sha256 "bd6e4434513ccf508b41765d9318d96cbb2c3464841d4c6c09a2acf92837895d"
      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  test do
    system "#{bin}/blue", "version"
  end
end
