# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlueCli < Formula
  desc "CLI for Blue workspace management"
  homepage "https://blue.cc"
  version "0.6.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyblueteam/cli/releases/download/v0.6.1/blue_darwin_amd64.tar.gz"
      sha256 "f24509c5ec6df413c0a2e230eb6890131dea28b06ef8ce0d9a6058d456cbabf7"

      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyblueteam/cli/releases/download/v0.6.1/blue_darwin_arm64.tar.gz"
      sha256 "30e59db55b6f273ebe79adb78bc1fb76e50fe9802eaedc7fe8f41a49c5295cc5"

      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.6.1/blue_linux_amd64.tar.gz"
      sha256 "9efc5f7b4f6ed38dda430c5c6a77bae4b070bb30c25a1f3d92bfe1fbdd5aced8"
      define_method(:install) do
        bin.install "blue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyblueteam/cli/releases/download/v0.6.1/blue_linux_arm64.tar.gz"
      sha256 "be5b4aaf5fb87b769919ac338d178c5346fb2d7ef33881fa653b5f17b0e80d0b"
      define_method(:install) do
        bin.install "blue"
      end
    end
  end

  test do
    system "#{bin}/blue", "version"
  end
end
