# This file was generated by GoReleaser. DO NOT EDIT.
cask "cobalt" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "3674062f562019266ad1491fbb768b9f94ed1bb227e93fa7dc5be0979e14f673"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "281120cea7022230e2a4e10ef1d36784de6bfcc06ae82de2210bf11527c54324"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  on_linux do
    on_intel do
      sha256 "90cdeb03da3202e139f654e3edcd8613e17eeda44109754413fd679996c022f6"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "72c65dd975e5afdf97fd1805efa520405cbb373b0d3efd2cfb48ec7f7a57ed05"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  name "cobalt"
  desc "Deployment glue for Docker Swarm + Caddy"
  homepage "https://cobalt.devel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cobalt"

  # No zap stanza required

end
