# This file was generated by GoReleaser. DO NOT EDIT.
cask "cobalt" do
  version "0.0.1-test"

  on_macos do
    on_intel do
      sha256 "e6009011beaea13ddd2a1c1f5a0b2131e957047bea4e1a5fa7a00c50ba4f7456"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "7f557ffc9bfcbf4a50e3fce005711dcfaacc46b9cccb056cf98c4c031a7f5da9"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a737a6440c59e6cf49700fd7c6cbab180b19268a48a933a35e362da55afdf2a"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "6d40a183388ebb3933c5e451b77a71bc80eec214c6bd35a3baa6b6f4bb6326e4"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  name "cobalt"
  desc "Deployment glue for Docker Swarm + Caddy"
  homepage "https://cobalt.devel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cobalt"

  # No zap stanza required

end
