# This file was generated by GoReleaser. DO NOT EDIT.
cask "cobalt" do
  version "0.9.4"

  on_macos do
    on_intel do
      sha256 "542833e3a04fcf88b439324a2e93952c1a49463240f0840494958736c49f1236"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "9650a8ccd9f2fe24f7895b804a506f12a1b9b6751fad78f39f1c564a02147a94"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  on_linux do
    on_intel do
      sha256 "99dc83fc78cb6bad6a92fee93862137c62bbd15294f1c42f56e2d49bd42111dc"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
    on_arm do
      sha256 "5318faa9d09d43fcdd11133375e7d8c802361e56e2498abf94cfe50f4746fbe4"
      url "https://github.com/heyblueteam/cobalt/releases/download/v#{version}/cobalt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/heyblueteam/cobalt"
    end
  end

  name "cobalt"
  desc "Deployment glue for Docker Swarm + Caddy"
  homepage "https://cobalt.devel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cobalt"

  # No zap stanza required

end
